### ISSUE TITLE
seen CADtest?

### ISSUE THREAD

**Issue by CADbloke** [wtertinek/AcadTestRunner#1]
Hi Mate

I just found your blog and this repo. have you seen https://github.com/CADbloke/CADtest ? It may help, show a different approach.

cheers
Ewen

**Comment by wtertinek** [comment]
Hi Ewen,

thank's for sharing your project! A nice approach. When I started this project I actually wanted to write a runner for an existing test framework, but I dind't really know how to do it. So I tried something on my own. Your project definitely gives me some new ideas.

Cheers,
Wolfgang
